### ISSUE TITLE
Training time is too long

### ISSUE THREAD

**Issue by fkeziyu** [alirezakazemipour/DIAYN-PyTorch#4]
Hello @alirezakazemipour,
Thanks for your code, I used your code in my env, but I met a question that the training time is too long.

My env is easy, but it need 3 days to train.

In the gym, how long did you need to get the result as you provided?

The RL algo is slow or my code is wrong？

**Comment by akazemipour** [comment]
Hi Thank you for your comment!

It's been a while since I wrote the code and many libraries have changed. That could contribute to make my code more inefficient. But I have not gotten any complaints so far about it being overly slow, barring yours. So, it could be more likely your implementation? 

I used to need to wait for just a couple of hours.

**Comment by fkeziyu** [comment]
ok, I see.

Thank you for your reply.

I will check my code.

**Comment by fkeziyu** [comment]
ok, I see.

Thank you for your reply.

I will check my code.
